[package]
name = "cargo-bup"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.18", features = ["derive"] }
clap_complete = "4.0.3"
crates-index = { version = "0.18.10", default-features = false }
git2 = "0.15.0"
hex = "0.4.3"
home = "0.5.4"
owo-colors = "3.5.0"
rayon = "1.5.3"
rustc_version = "0.4.0"
semver = "1.0.14"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
siphasher = "0.3.10"
tabled = { version = "0.10.0", features = ["color"] }
thread_local = "1.1.4"
url = "2.3.1"

[profile.release]
lto = true
strip = true
