[package]
name = "cargo-bup"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[dependencies]
anyhow = "1.0.58"
clap = { version = "3.2.14", features = ["derive"] }
clap_complete = "3.2.3"
crates-index = { version = "0.18.8", default-features = false }
git2 = "0.14.4"
hex = "0.4.3"
home = "0.5.3"
owo-colors = "3.4.0"
rayon = "1.5.3"
rustc_version = "0.4.0"
semver = "1.0.12"
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.82"
siphasher = "0.3.10"
tabled = { version = "0.8.0", features = ["color"] }
thread_local = "1.1.4"
url = "2.2.2"

[profile.release]
lto = true
strip = true
